import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "../api/client";

const ENV_OPTIONS = ["dev", "qa"];
const TABLES = ["accounts", "customers", "rules", "memberships"];

type Row = Record<string, unknown>;

function RowForm({
  schema,
  primaryKey,
  autoGenerated,
  initial,
  onSubmit,
  onCancel,
  mode,
}: {
  schema: { column_name: string; data_type: string; is_nullable: string }[];
  primaryKey: string[];
  autoGenerated: Set<string>;
  initial: Row;
  onSubmit: (data: Row) => void;
  onCancel: () => void;
  mode: "insert" | "update";
}) {
  const [values, setValues] = useState<Row>(initial);

  const set = (col: string, val: string) =>
    setValues((v) => ({ ...v, [col]: val }));

  return (
    <div className="space-y-3">
      <div className="grid grid-cols-2 gap-3">
        {schema
        .filter((col) => mode === "update" || !autoGenerated.has(col.column_name))
        .map((col) => {
          const isPk = primaryKey.includes(col.column_name);
          return (
            <div key={col.column_name}>
              <label className="block text-xs font-medium text-gray-600 mb-1">
                {col.column_name}
                <span className="ml-1 text-gray-400 font-normal">({col.data_type})</span>
                {isPk && <span className="ml-1 text-blue-500 font-normal">PK</span>}
              </label>
              <input
                type="text"
                value={values[col.column_name] !== undefined ? String(values[col.column_name]) : ""}
                onChange={(e) => set(col.column_name, e.target.value)}
                disabled={mode === "update" && isPk}
                placeholder={col.is_nullable === "YES" ? "null" : "required"}
                className="w-full text-sm border border-gray-300 rounded-lg px-3 py-2 disabled:bg-gray-100 disabled:text-gray-400"
              />
            </div>
          );
        })}
      </div>
      <div className="flex justify-end gap-2 pt-2">
        <button onClick={onCancel} className="px-4 py-2 text-sm text-gray-600 hover:text-gray-800">
          Cancel
        </button>
        <button
          onClick={() => onSubmit(values)}
          className="px-4 py-2 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700"
        >
          {mode === "insert" ? "Insert Row" : "Update Row"}
        </button>
      </div>
    </div>
  );
}

export function PlaygroundPage() {
  const [env, setEnv] = useState("dev");
  const [table, setTable] = useState("accounts");
  const [mode, setMode] = useState<"insert" | "update" | null>(null);
  const [editRow, setEditRow] = useState<Row>({});
  const [toast, setToast] = useState<{ msg: string; ok: boolean } | null>(null);
  const queryClient = useQueryClient();

  const showToast = (msg: string, ok: boolean) => {
    setToast({ msg, ok });
    setTimeout(() => setToast(null), 3000);
  };

  const { data: schemaData } = useQuery({
    queryKey: ["schema", env, table],
    queryFn: () => api.getTableSchema(env, table),
  });

  const { data: rowsData, refetch: refetchRows } = useQuery({
    queryKey: ["rows", env, table],
    queryFn: () => api.getTableRows(env, table),
  });

  const triggerPoll = () =>
    api.triggerPoll(env).then(() =>
      queryClient.invalidateQueries({ queryKey: ["changes", env] })
    );

  const insertMutation = useMutation({
    mutationFn: (data: Row) => api.insertRow(env, table, data),
    onSuccess: () => {
      showToast("Row inserted", true);
      setMode(null);
      refetchRows();
      triggerPoll();
    },
    onError: (e: Error) => showToast(e.message, false),
  });

  const updateMutation = useMutation({
    mutationFn: (data: Row) => api.updateRow(env, table, data),
    onSuccess: () => {
      showToast("Row updated", true);
      setMode(null);
      refetchRows();
      triggerPoll();
    },
    onError: (e: Error) => showToast(e.message, false),
  });

  const schema = schemaData?.schema ?? [];
  const primaryKey = schemaData?.primary_key ?? [];
  const rows = rowsData?.rows ?? [];
  const cols = schema.map((s) => s.column_name);

  // Hide auto-generated columns from insert form (serial PKs, timestamp defaults)
  const autoGenerated = new Set(
    schema
      .filter((c) =>
        c.column_default?.includes("nextval") ||
        c.column_default?.includes("now()")
      )
      .map((c) => c.column_name)
  );

  const emptyRow = Object.fromEntries(
    cols.filter((c) => !autoGenerated.has(c)).map((c) => [c, ""])
  );

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between">
        <span className="text-lg font-bold text-gray-900">light-cdc</span>
        <nav className="flex gap-4 text-sm text-gray-600">
          <a href="/" className="hover:text-gray-900">Dashboard</a>
          <a href="/snapshots" className="hover:text-gray-900">Snapshots</a>
          <a href="/playground" className="font-medium text-blue-600">Playground</a>
          <a href="/history" className="hover:text-gray-900">History</a>
        </nav>
      </header>

      <main className="max-w-5xl mx-auto px-6 py-8 space-y-6">
        {toast && (
          <div className={`rounded-lg px-4 py-3 text-sm border ${toast.ok ? "bg-green-50 border-green-200 text-green-800" : "bg-red-50 border-red-200 text-red-800"}`}>
            {toast.msg}
          </div>
        )}

        {/* Selectors */}
        <div className="flex items-center gap-3">
          <select value={env} onChange={(e) => { setEnv(e.target.value); setMode(null); }}
            className="text-sm border border-gray-300 rounded-lg px-3 py-2 bg-white">
            {ENV_OPTIONS.map((e) => <option key={e} value={e}>{e}</option>)}
          </select>
          <select value={table} onChange={(e) => { setTable(e.target.value); setMode(null); }}
            className="text-sm border border-gray-300 rounded-lg px-3 py-2 bg-white">
            {TABLES.map((t) => <option key={t} value={t}>{t}</option>)}
          </select>
          <button
            onClick={() => { setEditRow(emptyRow); setMode("insert"); }}
            className="ml-auto text-sm bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700"
          >
            + Insert Row
          </button>
        </div>

        {/* Form panel */}
        {mode && (
          <div className="bg-white rounded-xl border border-gray-200 p-5">
            <h2 className="text-sm font-semibold text-gray-900 mb-4 capitalize">
              {mode} into <span className="font-mono">{table}</span>
            </h2>
            <RowForm
              schema={schema}
              primaryKey={primaryKey}
              autoGenerated={autoGenerated}
              initial={editRow}
              mode={mode}
              onCancel={() => setMode(null)}
              onSubmit={(data) =>
                mode === "insert"
                  ? insertMutation.mutate(data)
                  : updateMutation.mutate(data)
              }
            />
          </div>
        )}

        {/* Rows grid */}
        <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
          <div className="px-5 py-4 border-b border-gray-100 flex items-center justify-between">
            <h2 className="text-sm font-semibold text-gray-900">
              {table} <span className="text-gray-400 font-normal">({rows.length} rows)</span>
            </h2>
            <p className="text-xs text-gray-400">Click a row to edit</p>
          </div>
          {rows.length === 0 ? (
            <p className="px-5 py-8 text-sm text-gray-400 text-center">No rows found</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-gray-50 text-xs uppercase tracking-wider text-gray-500">
                    {cols.map((c) => (
                      <th key={c} className="px-4 py-3 text-left font-medium whitespace-nowrap">
                        {c}
                        {primaryKey.includes(c) && <span className="ml-1 text-blue-400">PK</span>}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {rows.map((row, i) => (
                    <tr
                      key={i}
                      onClick={() => {
                        setEditRow(Object.fromEntries(
                          Object.entries(row).map(([k, v]) => [k, v === null ? "" : String(v)])
                        ));
                        setMode("update");
                      }}
                      className="hover:bg-blue-50 cursor-pointer transition-colors"
                    >
                      {cols.map((c) => (
                        <td key={c} className="px-4 py-3 font-mono text-xs text-gray-700 whitespace-nowrap">
                          {row[c] === null ? <span className="text-gray-300">null</span> : String(row[c])}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
